[package]
authors = ["ChiHai <ihciah@gmail.com>"]
description = "Http client for Monoio."
edition = "2021"
name = "monoio-http-client"
version = "0.0.1"

[dependencies]
monoio = {version = "0.0.7", path = "../../monoio/monoio"}
monoio-http = {version = "0.0.1", path = "../monoio-http"}
monoio-rustls = {version = "0.0.3", default_features = false, features = ["tls12"], path = "../../monoio-tls/monoio-rustls", optional = true}

bytes = "1"
http = "0.2"
local-sync = "0.0.5"
serde = "1"
serde_json = "1"
smol_str = "0.1"
thiserror = "1"

rustls = {version = "0.20", default-features = false, optional = true}
tracing = {version = "0.1", optional = true}
webpki-roots = {version = "0.22", optional = true}

[dev-dependencies]
serde = {version = "1", features = ["derive"]}
tracing = {version = "0.1"}
tracing-subscriber = {version = "0.3"}

[features]
default = ["tls", "unsafe-io", "time"]
# Enable this feature to make connection pool periodically checking works.
# You must enable time driver to use it.
time = []

logging = ["tracing", "monoio-rustls?/logging"]
tls = ["rustls", "webpki-roots", "monoio-rustls"]
unsafe-io = ["monoio-rustls?/unsafe_io"]
